In [1]:
import numpy as np , string

In [2]:
def readTextFile(path):
    plaintext_file = open(path,"r")
    plaintext = plaintext_file.read().split("\n")
    for i in range(len(plaintext)):
        if(plaintext[i] == ""):
            del plaintext[i]
    plaintext_file.close()
    return plaintext

In [3]:
def split(plain_text , n):
    splitted_plain_text = list("")
    for i in range(0 , len(plain_text) , n):
        splitted_plain_text.append(plain_text[i : i+n])

    for j in range(abs(len(splitted_plain_text[len(splitted_plain_text)-1]) - n)):    
        if(len(plain_text)%2 == 1 and n%2 == 1 or n%2 == 1):
            splitted_plain_text[len(splitted_plain_text)-1] += 'x'
        
    return splitted_plain_text

In [4]:
def hillCipher(plain_text , keyMatrix):
    R,C = keyMatrix.shape
    kMatrix = keyMatrix
    pMatrix = np.zeros((R,1) , dtype = np.int64)
    letters = string.ascii_uppercase
    cipher_text = ""
    
    splitted_plain_text = split(plain_text , C)
    
    for i in range(len(splitted_plain_text)):
        part = splitted_plain_text[i]
        r = 0
        for j in range(len(part)):
            pMatrix[r , 0] = letters.find(part[j])
            r += 1
            
        km = np.matrix(kMatrix)
        pm = np.matrix(pMatrix)
        result = (km * pm)%26
        
        for k in range(R):
            cipher_text += letters[int(str(result[k,:]).lstrip('[').rstrip(']'))]
    return cipher_text

In [5]:
hill_plainText_2x2 = readTextFile("Input Files\Hill\\hill_plain_2x2.txt")
hill_plainText_3x3 = readTextFile("Input Files\Hill\\hill_plain_3x3.txt")

k_2x2 = np.matrix(([[5 , 17],[8 , 3]]) , dtype= np.int64)
k_3x3 = np.matrix(([[2 , 4 , 12] , [9 , 1 , 6] , [7 , 5 , 3]]) , dtype=np.int64)

print("Hill Encryption with key = ")
print(str(k_2x2) + "\n")
for i in range(len(hill_plainText_2x2)):
    cipher_text_2x2 = hillCipher(hill_plainText_2x2[i] , k_2x2)
    with open('Hill Encryption\\2x2.txt','a') as txt:
        txt.write(cipher_text_2x2 + '\n')
        print("Plain text: " + hill_plainText_2x2[i] + " ==> Cipher text: " + cipher_text_2x2 +'\n')

print("----------------\n")

print("Hill Encryption with key = ")
print(str(k_3x3) + "\n")
for j in range(len(hill_plainText_3x3)):
    cipher_text_3x3 = hillCipher(hill_plainText_3x3[j] , k_3x3)
    with open('Hill Encryption\\3x3.txt','a') as txt:
        txt.write(cipher_text_3x3 + '\n')
        print("Plain text: " + hill_plainText_3x3[j] + " ==> Cipher text: " + cipher_text_3x3 +'\n')
        
print("----------------\n")      
print("Encryption completed successfully.")

Hill Encryption with key = 
[[ 5 17]
 [ 8  3]]

Plain text: VVMSQFGA ==> Cipher text: UXCUJNEW

Plain text: IUETTRZQ ==> Cipher text: QUFLUVHO

Plain text: DAKYTDGF ==> Cipher text: PYQWQFLL

Plain text: VQUNPMHV ==> Cipher text: NIJRTACP

----------------

Hill Encryption with key = 
[[ 2  4 12]
 [ 9  1  6]
 [ 7  5  3]]

Plain text: YGREBGHZ ==> Cipher text: QMPGVZYEP

Plain text: BKDLPUKN ==> Cipher text: ALOKAEITC

Plain text: FSSZULIH ==> Cipher text: MPXCZWGVK

Plain text: JFOXRSFQ ==> Cipher text: YOASUOKDI

----------------

Encryption completed successfully.
